sh ./install-type.sh axios
sh ./install-type.sh babel-cli
sh ./install-type.sh babel-core
sh ./install-type.sh body-parser
sh ./install-type.sh chalk
sh ./install-type.sh commander
sh ./install-type.sh cookie-parser
sh ./install-type.sh csv
sh ./install-type.sh d3v4
sh ./install-type.sh domhandler
sh ./install-type.sh domutils
sh ./install-type.sh express
sh ./install-type.sh express-session
sh ./install-type.sh gps-distance
sh ./install-type.sh htmlparser
sh ./install-type.sh htmlparser2
sh ./install-type.sh jsdom
sh ./install-type.sh module-alias
sh ./install-type.sh node
sh ./install-type.sh node-csv
sh ./install-type.sh passport
sh ./install-type.sh passport-local
sh ./install-type.sh passport-meetup
sh ./install-type.sh passport-strategy
sh ./install-type.sh rxjs
sh ./install-type.sh serve-static
sh ./install-type.sh ts-keycode-enum
sh ./install-type.sh tslib
sh ./install-type.sh tslint
sh ./install-type.sh tslint-config-standard
sh ./install-type.sh tslint-eslint-rules
sh ./install-type.sh typescript
