sh ./install-type.sh body-parser
sh ./install-type.sh cookie-parser
sh ./install-type.sh express
sh ./install-type.sh express-session
sh ./install-type.sh node
sh ./install-type.sh passport
sh ./install-type.sh passport-local
sh ./install-type.sh passport-meetup
sh ./install-type.sh passport-strategy
sh ./install-type.sh request
sh ./install-type.sh serve-static
sh ./install-type.sh axios
sh ./install-type.sh body-parser
sh ./install-type.sh cookie-parser
sh ./install-type.sh express
sh ./install-type.sh express-session
sh ./install-type.sh htmlparser
sh ./install-type.sh passport
sh ./install-type.sh passport-local
sh ./install-type.sh passport-meetup
sh ./install-type.sh request
sh ./install-type.sh rxjs
sh ./install-type.sh serve-static
sh ./install-type.sh ts-keycode-enum
sh ./install-type.sh tslib
sh ./install-type.sh tslint
sh ./install-type.sh tslint-config-standard
sh ./install-type.sh tslint-eslint-rules
sh ./install-type.sh typescript
